// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  alternating_text: dynamic(() => import("./AlternatingText")),
  carousel: dynamic(() => import("./Carousel")),
  first: dynamic(() => import("./Hero")),
};
